version: '3.8'

services:
  app:
    image: '9697cd6b353a'
    container_name: app
    ports:
      - '8080:8080'
    environment:
          - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/asthomeworkdb
          - SPRING_DATASOURCE_USERNAME=postgres
          - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
        - db
  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=asthomeworkdb
    ports:
      - '5432:5432'
