version: '3.8'

services:
  user-service:
    build:
      context: ../homework
      dockerfile: docker/Dockerfile
    container_name: user-service
    ports:
      - '8080:8080'
    environment:
          - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/asthomeworkdb
          - SPRING_DATASOURCE_USERNAME=postgres
          - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
        - db
        - kafka
  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=asthomeworkdb
    ports:
      - '5432:5432'

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
        - zookeeper
    ports:
        - "9092:9092"
    environment:
        - KAFKA_CFG_PROCESS_ROLES=controller,broker
        - KAFKA_CFG_NODE_ID=1
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
        - ALLOW_PLAINTEXT_LISTENER=yes

  notification-service:
      build:
        context: ../notification-service
        dockerfile: docker/Dockerfile
      container_name: consumer-service
      depends_on:
        - kafka
      environment:
        - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092